import React from 'react'

const glossary = [
  "Absolute – A highly concentrated, fragrant oil extracted from plants.",
  "Accord – A blend of notes that create a unified scent impression.",
  "Aldehyde – Synthetic chemicals used to add sparkle and lift to perfumes.",
  "Amber – A warm, sweet, resinous accord often used in oriental fragrances.",
  "Animalic – Scent notes reminiscent of animal odors, adding depth and sensuality.",
  "Anosmia – Loss or absence of the sense of smell.",
  "Aromatic – Fragrances with herbal, spicy, or camphoraceous notes.",
  "Base Note – The last phase of a perfume, which lingers the longest.",
  "Balsamic – Notes that are warm, sweet, resinous, and soothing.",
  "Bergamot – A citrus fruit oil with a fresh, slightly spicy scent.",
  "Blend – The harmonious combination of different perfume ingredients.",
  "Body – The main theme or middle part of a fragrance.",
  "Bouquet – A complex blend of floral notes.",
  "Chypre – A fragrance family with oakmoss, labdanum, and citrus.",
  "Civet – Animalic note once derived from the civet cat; now mostly synthetic.",
  "Citrus – Fragrances based on lemon, orange, lime, etc.",
  "Clary Sage – A herbaceous note with tea and amber undertones.",
  "Cloying – Overly strong or sweet scent that can be unpleasant.",
  "Cold Throw – The scent of a candle or solid perfume before being heated.",
  "Cologne – A light fragrance, typically with 2–5% perfume oil.",
  "Compound – The mixture of all perfume ingredients before dilution.",
  "Concentration – The ratio of perfume oil to alcohol or solvent.",
  "Creamy – A smooth, soft, lactonic scent texture.",
  "Creed – A term also used to describe a signature fragrance or style.",
  "Crisp – Sharp, clean, fresh scent profile.",
  "Cruelty-Free – Products not tested on animals.",
  "Crystalline – Transparent, sparkling, fresh-like scent.",
  "Cypriol – An earthy, woody note from Indian papyrus.",
  "Davana – A fruity, herbal, slightly boozy note.",
  "Decant – A small sample bottle taken from a larger one.",
  "Diffuse – The ability of a scent to spread into the air.",
  "Dirty – A scent with earthy, raw, or animalic tones.",
  "Distillation – Extraction of essential oils using steam or heat.",
  "Dry Down – The final scent phase of a perfume on skin.",
  "Earthy – A scent reminiscent of soil, roots, and nature.",
  "Eau de Cologne – Low-concentration fragrance with citrus emphasis.",
  "Eau de Parfum (EdP) – Moderate concentration (10–20%) with longer longevity.",
  "Eau de Toilette (EdT) – Lighter than EdP; lasts 4–6 hours.",
  "Elixir – A rich, highly concentrated scent or formula.",
  "Enfleurage – Old technique using fat to absorb floral oils.",
  "Essential Oil – Natural aromatic oil extracted from plants.",
  "Ethereal – Light, airy, and delicate aroma.",
  "Extrait – The most concentrated form of perfume.",
  "Exotic – A scent with foreign, spicy, or unusual notes.",
  "Feminine – Scents marketed traditionally toward women.",
  "Fixative – Ingredient that stabilizes volatile oils and extends longevity.",
  "Flacon – A decorative perfume bottle.",
  "Flat – A fragrance lacking complexity or projection.",
  "Floral – A dominant scent family with flower-based notes.",
  "Fougère – A family with lavender, oakmoss, and coumarin.",
  "Fresh – Clean, airy, uplifting scents like citrus and greens.",
  "Fruity – Scents inspired by fruits other than citrus.",
  "Gourmand – Edible-like scents (vanilla, chocolate, caramel).",
  "Green – Notes that evoke leaves, grass, and herbs.",
  "Harsh – Overpowering, unbalanced, or synthetic scent.",
  "Heart Note – The main scent body that emerges after the top note fades.",
  "Hesperidic – Related to citrus fruits like bergamot and lemon.",
  "Herbaceous – Aromatic green notes from herbs.",
  "Honeyed – Sweet, warm, and nectar-like scent.",
  "Incense – A smoky, resinous note from burning resins.",
  "Indolic – A floral note with animalic or dirty facets.",
  "Infusion – Method of extracting fragrance using a solvent.",
  "Intense – A stronger version of an existing fragrance.",
  "Iris – A powdery, woody floral note from iris root.",
  "Jasmine – A rich, white floral note used widely in perfumery.",
  "Juicy – A fresh, succulent, fruity scent character.",
  "Labdanum – A sweet, leathery resin used in amber accords.",
  "Lactonic – Creamy, milky notes reminiscent of coconut or peach.",
  "Layering – Combining multiple scents to create a custom blend.",
  "Leather – A dry, smoky scent inspired by tanned hides.",
  "Legere – A lighter, fresher version of a fragrance.",
  "Lift – The brightness or openness a note gives to a blend.",
  "Linear – A scent that smells the same from start to finish.",
  "Longevity – The duration a perfume remains noticeable.",
  "Luminous – A scent that feels radiant and airy.",
  "Masculine – Scents marketed traditionally toward men.",
  "Middle Note – See Heart Note.",
  "Mineral – Clean, cool, stony-like scent character.",
  "Misty – A soft, dewy, subtle scent texture.",
  "Modern – Contemporary scents often using synthetic molecules.",
  "Mossy – Earthy, damp forest notes like oakmoss.",
  "Muguet – French for lily-of-the-valley.",
  "Musk – A soft, warm base note once derived from deer, now synthetic.",
  "Narcotic – An intoxicating, rich floral note (like tuberose or jasmine).",
  "Natural – Scent materials derived from plants, animals, or minerals.",
  "Neroli – Distilled oil from bitter orange blossoms.",
  "Niche – Artisanal or non-mainstream perfumes with unique compositions.",
  "Note – An individual scent component.",
  "Nutty – A warm, dry scent reminiscent of nuts.",
  "Olfactory – Pertaining to the sense of smell.",
  "Opulent – Rich, full-bodied, and luxurious scent.",
  "Oriental – Warm, spicy, and often sweet fragrance family.",
  "Orris – Fragrance note from the iris root.",
  "Oud – A dark, resinous wood from agarwood trees.",
  "Overdose – When a note is used in very high concentration.",
  "Ozonic – Fresh, airy notes that mimic sea breeze or air.",
  "Pheromone – Chemicals believed to trigger attraction responses.",
  "Powdery – Soft, talc-like scent impression.",
  "Projection – How far a perfume travels from the skin.",
  "Pure Perfume – See Extrait.",
  // --- Added items below ---
  "Raw Material – The original ingredient used in perfume creation.",
  "Resin – Sticky plant secretion used for deep, balsamic notes.",
  "Rich – A full, complex, and opulent fragrance profile.",
  "Rindy – Sharp, bitter citrus peel note.",
  "Rose – One of the most classic floral notes, sweet and romantic.",
  "Rustic – Earthy and natural smelling, often unrefined.",
  "Saffron – A spicy, leathery, slightly metallic note.",
  "Sandalwood – A creamy, woody base note with soft warmth.",
  "Savory – Herbal or spicy notes that aren’t sweet.",
  "Scent – General term for a smell or perfume.",
  "Sharp – A piercing or intense top note.",
  "Sheer – Light, airy, and transparent scent texture.",
  "Silage – See Sillage.",
  "Silky – Smooth and soft scent impression.",
  "Sillage – The trail a fragrance leaves behind.",
  "Skin Scent – A fragrance that wears close to the body.",
  "Smoky – A burnt or incense-like quality in perfume.",
  "Soft – A gentle, non-intrusive scent.",
  "Soliflore – A fragrance built to highlight a single floral note.",
  "Solvent – The liquid base (like alcohol) that carries the fragrance.",
  "Soapy – Clean, often aldehydic note reminiscent of soap.",
  "Sparkling – Bright and effervescent top notes.",
  "Spicy – Warm, pungent notes like cinnamon, clove, or pepper.",
  "Splash – A light perfume meant to be applied generously.",
  "Spray – A perfume delivery method using a pump or aerosol.",
  "Stewed – Fruity notes that are warm and cooked-like.",
  "Stingy – Poor projection or low concentration.",
  "Styrax – A resin with sweet, balsamic qualities.",
  "Suede – A softer take on leather notes.",
  "Sugar – A sweet, crystalline note often used in gourmands.",
  "Sun-kissed – Warm, glowing scent impression.",
  "Sweet – A sugary or candied scent profile.",
  "Synthetic – Lab-created ingredients not found in nature.",
  "Tangy – Sharp, zesty citrus or fruit note.",
  "Tannic – A dry, bitter aroma like black tea.",
  "Tart – Sour or tangy scent like unripened fruit.",
  "Tea – A green, dry, aromatic note.",
  "Tenacity – The staying power of a fragrance on the skin.",
  "Texture – The feel or shape of a scent (e.g., creamy, dry).",
  "Tincture – An infusion made by soaking material in alcohol.",
  "Tobacco – A warm, dry, sweetly smoky note.",
  "Tonka Bean – A vanilla-like, warm, sweet gourmand note.",
  "Top Note – The first impression of a perfume.",
  "Transparent – Light and airy scent composition.",
  "Treemoss – Earthy, forest-like note used in chypres.",
  "Tuberose – A rich, narcotic white floral note.",
  "Undertone – Subtle or supporting scent in a fragrance.",
  "Unisex – Designed for any gender.",
  "Uplifting – A scent that evokes positivity and energy.",
  "Vanilla – A sweet, warm, comforting gourmand note.",
  "Vegetal – Plant-like, green, earthy scent quality.",
  "Velvety – Smooth and lush scent texture.",
  "Vetiver – A green, earthy, woody grass used as a base note.",
  "Vibrant – Lively, energetic scent character.",
  "Violet Leaf – A green, watery floral note.",
  "Volatile – Easily evaporated, short-lived top notes.",
  "Warm – Scent that gives a cozy or heated impression.",
  "Water Note – Aquatic, marine, or dewy fresh accord.",
  "Wax Melt – A solid form of fragrance melted for scent.",
  "White Floral – Category of flowers with narcotic intensity (e.g., jasmine, tuberose).",
  "Whiff – A brief or light scent.",
  "Woody – Dry, resinous notes from trees (cedar, sandalwood).",
  "Ylang-Ylang – A tropical floral note, rich and exotic.",
  "Zesty – Lively, citrusy, tangy top note.",
  "Zingy – Sharp, citrusy, and energetic scent.",
  "Zodiac Perfume – Scent based on astrological signs.",
  "Dry – Scent with little sweetness, often woody.",
  "Faint – Barely noticeable scent.",
  "Bright – High-pitched, citrusy or aldehydic tone.",
  "Ashy – A smoky or burnt note.",
  "Boozy – Alcohol-like scent note (rum, cognac, whiskey).",
  "Caramel – A sticky sweet gourmand note.",
  "Dusty – Slightly dry, powdery scent.",
  "Ginger – Spicy, fresh, citrus-like note.",
  "Icy – Cool, frosty, menthol-like scent.",
  "Meaty – Dense, heavy, animalic or savory scent.",
  "Metallic – Sharp, synthetic note with a cold edge.",
  "Nutmeg – Spicy, sweet, warm note.",
  "Pine – Sharp, resinous, evergreen tree aroma.",
  "Plush – Luxurious and dense scent texture.",
  "Rainy – A cool, fresh aquatic scent.",
  "Rubbery – Industrial, synthetic scent nuance.",
  "Syrupy – Thick, sweet, often cloying scent.",
  "Resplendent – Radiant, glowing scent profile.",
  "Wholesome – Clean, comforting scent.",
  "Yuzu – A Japanese citrus with tart, fragrant zest.",
  "Cactus – Green, watery plant note.",
  "Bamboo – Fresh, woody-green note.",
  "Basenote – See Base Note.",
  "Pungent – Strong, sharp, or biting scent.",
  "Green Tea – Light, dry, calming herbal note.",
  "Hay – Dry, herbal note with sweet, grassy facets.",
  "Licorice – Sweet, anise-like gourmand or herbal note.",
  "Lime – Sharp, citrus top note.",
  "Oceanic – Fresh, clean marine fragrance.",
  "Plastic – Synthetic note with a vinyl-like smell.",
  "Powder – See Powdery.",
  "Rainforest – Green, damp, earthy complex scent.",
  "Stone – Cool, mineral-like accord.",
  "Sunflower – A soft, slightly nutty floral scent.",
  "Sweetgrass – A vanilla-like grassy note used in earthy blends.",
  "Tincturing – Creating scent by soaking materials in alcohol.",
  "Vanillin – The primary component of vanilla bean scent.",
  "Varnish – A sharp, glossy synthetic aroma.",
  "Waxy – Lipid-like, creamy, dense scent.",
  "Airy – Light, spacious scent composition.",
  "Anise – Licorice-like, spicy-sweet note.",
  "Ash – Burnt, mineral, or smoky note.",
  "Basil – Spicy-green herbaceous note.",
  "Beeswax – A sweet, waxy note from natural honeycomb.",
  "Bread – Yeasty, doughy scent note.",
  "Burnt Sugar – A warm, caramelized gourmand scent.",
  "Buttery – Smooth, fatty scent, often used in gourmands.",
  "Camphor – Cool, medicinal note found in eucalyptus.",
  "Caraway – Spicy, herbaceous seed note.",
  "Celery Seed – Bitter, green herbal spice note.",
  "Chalky – Dry, powdery mineral-like scent.",
  "Champaca – Exotic floral with tea and spice nuances.",
  "Chili – Hot peppery accord in spicy perfumes.",
  "Chypre Accord – Combination of bergamot, oakmoss, labdanum, patchouli.",
  "Cinnamon – Sweet-spicy, warm note.",
  "Cistus – A resinous floral note from the rock rose plant.",
  "Clementine – Sweet, juicy citrus top note.",
  "Coconut – Creamy, tropical fruit note.",
  "Coffee – Bitter, roasted gourmand scent.",
  "Concrete – A waxy perfume material extracted with solvents.",
  "Crystalline Musk – Transparent, clean musk note.",
  "Cucumber – Watery, crisp green note.",
  "Cumin – Warm, spicy, slightly animalic note.",
  "Currant – Tart, fruity note (often blackcurrant).",
  "Cyclamen – Light, green, watery floral note.",
  "Damp – Wet earth or musty scent profile.",
  "Date – Sweet, sticky dried fruit note.",
  "Dewy – Watery, light freshness.",
  "Driftwood – Soft, salty-woody aquatic note.",
  "Earl Grey – Tea and bergamot blend note.",
  "Edelweiss – Clean, fresh alpine floral.",
  "Eucalyptus – Minty, cool, medicinal note.",
  "Featherlight – Extremely subtle, airy scent.",
  "Fennel – Sweet, herbaceous aniseed-like note.",
  "Fern – Green fougère note, forest-like.",
  "Fig – Sweet, milky, fruity-green note.",
  "Fir Balsam – Resinous evergreen forest note.",
  "Flint – Dry, mineral note resembling stone.",
  "Flesh – A warm, soft, musky skin scent.",
  "Foggy – Hazy, soft, and muted scent impression.",
  "Frozen – Icy, mentholated cool scent.",
  "Fruity Floral – Blend of fruit and floral notes.",
  "Gardenia – Creamy, lush white floral note.",
  "Gasoline – Sharp, industrial synthetic note.",
  "Geranium – Bright, green-rosy floral note.",
  "Gin – Crisp, herbaceous alcohol note.",
  "Gooseberry – Tart, green fruit note.",
  "Graphite – Dry, pencil-like mineral note.",
  "Green Apple – Crisp, tart fruity top note.",
  "Gris – Grey-like scent tone: powdery, musky, metallic.",
  "Guaiac Wood – Smoky, woody resin note.",
  "Gum Resin – Natural resin from trees, used in incense.",
  "Hay Absolute – Sweet, grassy base note.",
  "Heliotrope – Powdery, almond-vanilla floral note.",
  "Hemp – Earthy, nutty-green herbal scent.",
  "Herbal – Notes from culinary or medicinal herbs.",
  "Himalayan Cedar – Soft, woody cedar variant.",
  "Hinoki – Japanese cypress with citrus and wood tone.",
  "Honey – Sweet, animalic nectar note.",
  "Hops – Bitter, green beer-like scent.",
  "Ice – See Icy.",
  "Indian Spices – Warm, exotic spice blend.",
  "Inky – Dark, dry note resembling ink or paper.",
  "Iron – Metallic, mineral note.",
  "Ivy – Fresh, green, climbing-plant scent.",
  "Jaggery – Caramel-like raw sugar note.",
  "Juniper – Fresh, piney note used in gin.",
  "Kumquat – Zesty, sweet citrus fruit.",
  "Laurel – Warm, spicy herbal note.",
  "Lavandin – A hybrid of lavender with sharper profile.",
  "Lentisque – Green resinous Mediterranean shrub note.",
  "Lily – Bright white floral, often fresh or waxy.",
  "Linden Blossom – Sweet, green-floral honeyed note.",
  "Liquor – Boozy scent (rum, whiskey, etc.).",
  "Lotus – Water floral, dewy and delicate.",
  "Mahogany – Dark, rich wood note.",
  "Mandarin – Soft, sweet citrus top note.",
  "Maple – Sweet, woody syrupy note.",
  "Marzipan – Sweet almond-paste note.",
  "Mate – Earthy, green tea note.",
  "Meadow – Green-floral, grassy open field note.",
  "Menthol – Cool, minty aromatic.",
  "Metal – Industrial, cool, synthetic tone.",
  "Milk – Lactonic creamy gourmand note.",
  "Mineralic – See Mineral.",
  "Mint – Cool, refreshing green herb.",
  "Mojito – Lime, mint, and rum-inspired blend.",
  "Molasses – Dark, syrupy sweet note.",
  "Monoi – Tiare flower in coconut oil base.",
  "Myrtle – Sweet, herbaceous Mediterranean note.",
  "Nag Champa – Indian incense blend.",
  "Narcissus – Sweet, heady floral with green nuance.",
  "Nutmeg Flower – Spicy floral version of nutmeg.",
  "Oak – Dry, woody forest base note.",
  "Oakmoss Absolute – Deep, earthy forest base note.",
  "Olive Leaf – Green, savory note.",
  "Onion Flower – Sharp, sulfuric floral tone.",
  "Opoponax – Sweet myrrh resin note.",
  "Orange Blossom – Sweet, white floral citrus note.",
  "Oregano – Spicy, green herbaceous note.",
  "Orgeat – Almond syrup gourmand note.",
  "Ozone – See Ozonic.",
  "Papyrus – Dry, woody, earthy scent.",
  "Paraffin – Waxy, neutral candle-like note.",
  "Patchouli – Earthy, damp, musky-sweet base note.",
  "Peach – Sweet, juicy fruit note.",
  "Pear – Fresh, crisp, sweet fruit.",
  "Peony – Light, rosy-pink floral note.",
  "Pepper – Spicy, sharp note (black, pink, white).",
  "Pineapple – Tropical, juicy sweet fruity note.",
  "Pink Sugar – Candyfloss-like gourmand sweetness.",
  "Pistachio – Nutty, sweet gourmand nuance.",
  "Pomegranate – Tart, juicy red fruit note.",
  "Popcorn – Buttery, salty gourmand note.",
  "Pumpkin – Warm, spiced autumnal note.",
  "Quince – Tart, green-yellow fruity note.",
  "Raspberry – Sweet, tangy red fruit note.",
  "Red Currant – Tart, sharp red berry.",
  "Resinoid – Extracted thick perfume resin.",
  "Rice – Soft, starchy sweet base note.",
  "Rooibos – Red tea with earthy, sweet tone.",
  "Rosewood – Soft, floral woody note.",
  "Rum – Sweet, boozy note with depth.",
  "Sage – Aromatic herbal note.",
  "Salt – Mineral, marine, savory nuance.",
  "Seaweed – Green marine scent with umami edge.",
  "Sesame – Nutty, oily gourmand note.",
  "Shiso – Herbal, minty Japanese leaf note.",
  "Skin Musk – Barely-there, clean musk.",
  "Smoldering – Slow-burning, smoky scent nuance.",
  "Snowdrop – Clean, white floral note.",
  "Soap Accord – Synthetic mix mimicking clean soap.",
  "Sorbet – Cool, fruity gourmand note.",
  "Spearmint – Sweeter, softer mint variety.",
  "Spikenard – Ancient, woody resin note.",
  "Star Anise – Sharp, spicy licorice note.",
  "Strawberry – Sweet, juicy red fruit note.",
  "Sugar Cane – Raw sweetener, clean sweet note.",
  "Sunburnt Skin – Hot skin, creamy, salty musk accord.",
  "Tamarind – Sweet-sour tropical fruit note.",
  "Tangerine – Juicy, sweet citrus.",
  "Tea Leaf – Dry, green herbal note.",
  "Terracotta – Warm, mineral-earthy nuance.",
  "Thyme – Sharp, green herbal spice.",
  "Toffee – Buttery caramelized sugar note.",
  "Tomato Leaf – Sharp, green vegetal note.",
  "Truffle – Earthy, musky gourmand note.",
  "Turmeric – Warm, spicy root note.",
  "Turned Earth – Rich, dark earthy accord.",
  "Vanilla Orchid – Floral version of vanilla.",
  "Vetiver Bourbon – Smokier, sweeter type of vetiver.",
  "Vine Leaf – Green, herbal grape leaf scent.",
  "Wheat – Warm, nutty grain note.",
  "Whipped Cream – Light, airy gourmand sweetness.",
  "White Musk – Clean, modern synthetic musk.",
  "Wild Strawberry – Tart, forest fruit note.",
  "Wine – Red or white grape boozy note.",
  "Wood Smoke – Burning, dry, natural wood scent.",
  "Wormwood – Bitter, green herbal note.",
  "Yam – Sweet, starchy gourmand note.",
  "Yellow Flowers – Rich, pollen-heavy floral category.",
  "Zephyr – Gentle, soft scent breeze.",
  "Aromatic Fougere – Fougère with spicy herbaceous lift.",
  "Aromatic Citrus – Fresh citrus with herbal undertone.",
  "Ambergris – Oceanic musk from whale, now synthetic.",
  "Birch Tar – Smoky leather note.",
  "Cassie – Powdery mimosa-like floral note.",
  "Cedar Leaf – Sharp, green coniferous note.",
  "Frangipani – Sweet tropical floral with creamy fruitiness.",
  "Galbanum – Sharp, bitter green resin.",
  "Grapefruit – Tart, bitter citrus top note.",
  "Immortelle – Curry-like, maple-sweet floral.",
  "Iso E Super – Woody synthetic molecule with soft projection.",
  "Khus – Indian name for vetiver.",
  "Linalool – Floral, spicy aroma compound.",
  "Mimosa – Soft, powdery yellow floral.",
  "Myrrh – Bitter resin used in incense.",
  "Nerolidol – Woody floral compound found in orange blossom.",
  "Oakwood – Dry, woody forest note.",
  "Phenol – Smoky, tarry chemical note.",
  "Red Cedar – Warm, rich wood note.",
  "Safraleine – Synthetic saffron-spice molecule.",
  "Sclareol – Natural fixative in clary sage.",
  "Tolu Balsam – Warm vanilla-cinnamon resin.",
  "Verdant – Rich green scent.",
  "Violet – Sweet, powdery, soft floral.",
  "Ylang Essence – Concentrated ylang-ylang extract.",
  "Zest – Citrus peel note.",
  "Ambroxan – Synthetic ambergris molecule.",
  "Cashmeran – Musky-woody-sweet synthetic note.",
  "Hedione – Fresh jasmine-like molecule.",
  "Helional – Marine, fresh synthetic molecule.",
  "Calone – Sea breeze synthetic molecule.",
  "Lyral – Floral synthetic, now restricted.",
  "Vert de Fleur – A green floral accord.",
  "Amber Accord – A blend of labdanum, benzoin, and vanilla.",
  "Marine Notes – Ocean-inspired, salty-fresh notes.",
  "Desert Accord – Dry, dusty, sun-baked scent profile.",
  "Frozen Citrus – Icy, sharp lemon-lime type note.",
  "Cold Spice – Peppery or herbal with cooling elements.",
  "Desiccated – Dried-out or dehydrated scent style.",
  "Digital – Clean, sterile, synthetic perfume trend.",
  "Ink Accord – Notes mimicking pen ink or marker.",
  "Laundry Musk – Clean, crisp, soapy musk.",
  "Powder Accord – Talcum, iris, heliotrope mix.",
  "Smoked Tea – Lapsang souchong–inspired smoky tea note.",
  "Amberwood – Woody-ambery synthetic used for warmth.",
  "Gingerbread – Spiced sweet gourmand.",
  "Labdanum Resin – A deep, sticky amber resin.",
  "Damp Earth – Wet soil accord.",
  "Vintage Note – Old-school musks or aldehydes evoking retro style.",
  "Metallic Floral – Synthetic sharpness in white florals.",
  "Vetiver Haiti – Clean, green version of vetiver.",
  "Sueded Rose – Rose paired with soft suede notes.",
  "Mineral Musk – Cold, salty, and clean musk type.",
  "Benzoin – Sweet, vanilla-like resin.",
  "Crushed Leaves – Green broken foliage scent.",
  "Forest Floor – Earthy, mossy, damp scent.",
  "Moss Accord – Oakmoss-inspired base without allergens.",
  "Desert Rose – Warm, dry rose with spices.",
  "Ozone Accord – Sky-air-inspired synthetic.",
  "Latex – Rubber-like scent.",
  "Vinyl – Plastic-like synthetic scent.",
  "Crème Brûlée – Burnt sugar custard scent.",
  "Walnut – Dry, woody nut note.",
  "Cool Spices – Cardamom, coriander in icy blends.",
  "Ambergris Accord – Marine-musky synthetic blend.",
  "Chili Chocolate – Spicy cocoa gourmand.",
  "Electric Citrus – Sharp, synthetic lemon/lime.",
  "Grilled Fruit – Smoky-sweet fruit notes.",
  "Resinous Amber – Deep amber dominated by labdanum.",
  "Burnt Oud – Smoky, resin-rich oud.",
  "Desert Sand – Dry, dusty mineral accord.",
  "Old Books – Paper, leather, ink combo.",
  "Green Tobacco – Fresh leafy tobacco before curing.",
  "Pink Pepper – Fruity, spicy pepper note.",
  "Ginger Blossom – Floral-spicy blend.",
  "Savannah Grass – Dry wild grass accord.",
  "Baklava – Nutty, honeyed pastry note.",
  "Blond Woods – Light, clean wood note.",
  "Cement – Dry, mineral urban scent.",
  "Crisp Linen – Fresh laundry-like note.",
  "Vin Santo – Italian dessert wine scent.",
  "Ink Paper – Paper and ink nostalgic accord.",
  "Spring Air – Floral, green, airy blend.",
  "Mineral Water – Sparkling aquatic mineral note.",
  "Lactic Accord – Milky-creamy molecule.",
  "Crème Accord – Soft creamy gourmand base.",
  "Golden Amber – Rich, sweet amber accord.",
  "Carrot Seed – Earthy-floral root note.",
  "Wet Cement – Fresh-poured concrete accord.",
  "Steam Accord – Warm misty scent.",
  "Cactus Water – Green watery floral.",
  "Raw Leather – Animalic leather scent.",
  "Powdered Sugar – Light sugary gourmand.",
  "Ice Cream – Vanilla-cold creamy scent.",
  "Champagne Accord – Effervescent fruity sparkle.",
  "Sugar Crystal – Crunchy sweet gourmand note.",
  "Cotton Flower – Soft, fabric-clean floral.",
  "Roasted Nuts – Warm dry nutty gourmand.",
  "Toasted Coconut – Sweet, creamy gourmand coconut.",
  "Ethereal Musk – Transparent, airy musk.",
  "Worn Denim – Clean, musky textile scent.",
  "Hot Stone – Mineral accord with solar warmth.",
  "Cereal – Grainy sweet milk breakfast note.",
  "Cherry Blossom – Delicate, sweet floral.",
  "Linen Musk – Textile-clean with soft musky base.",
  "Salted Caramel – Sweet-salty gourmand trend.",
  "Rice Milk – Milky, lactonic soft scent.",
  "Golden Wood – Warm, dry woody accord.",
  "Blue Tea – Delicate floral tea blend.",
  "Ashen Wood – Burnt woody smoke note.",
  "Wheat Field – Dry grassy-sweet scent.",
  "Honeycomb – Sweet, waxy floral.",
  "Snow Accord – Icy, fresh synthetic note.",
  "White Tea – Light, airy, floral tea note.",
  "Sunlit Skin – Warm musky-solar floral accord.",
  "Crushed Peony – Bright green floral burst.",
  "Hazy Musk – Fuzzy, soft background musk.",
  "Iced Violet – Cold floral powdery accord.",
  "Cloud Accord – Airy-soft scent illusion.",
  "Sun Drenched Linen – Warm, clean cotton note.",
  "Ocean Drift – Salty aquatic breeze.",
  "Burning Resin – Smoky amber incense accord.",
  "Cool Leather – Leather with airy or ozonic overlay.",
  "Spiced Cream – Warm, sweet spice-lactonic blend.",
  "Skin Warmth – Subtle musk with heat activation.",
  "Iced Neroli – Fresh citrus with menthol twist.",
  "Charred Wood – Burnt woody base.",
  "Solar Accord – Warm, radiant sunlit impression.",
  "Peach Blossom – Fruity-floral soft note.",
  "Dust Accord – Dry, musky-powdery nuance.",
  "Resin Smoke – Heavy incense-rich resin note.",
  "Dried Petals – Floral decay with a dry, vintage edge.",
  "Rusace: Brand Name for Perfume - is made of the first two letters of the Names : Ruba Sarah Celine"
];

const page = () => {
  return (
    <div style={{ textAlign: 'left', padding: '2rem', maxWidth: '900px', margin: 'auto' , marginTop:'5em'}} >
      <h2 className='mb-5'>Perfume Glossary</h2>
<div>
  {glossary.map((item, idx) => (
    <div key={idx} style={{ display: 'flex', marginBottom: '0.5rem' }}>
      <span style={{ marginRight: '0.5rem' }}>{idx + 1}.</span>
      <span>{item}</span>
    </div>
  ))}
</div>



    </div>
  );
}

export default page